<?xml version="1.0" encoding="UTF-8"?>

<!-- File was generated by XSLfast 6.0, build 11/09/2012 -->
<!-- Layout version: 0 -->
<!-- Please leave unchanged; manage layouts instead -->
<!DOCTYPE xsl:stylesheet [
<!ENTITY XML "http://www.w3.org/TR/REC-xml">
<!ENTITY XMLNames "http://www.w3.org/TR/REC-xml-names">
<!ENTITY XSLT.ns "http://www.w3.org/1999/XSL/Transform">
<!ENTITY XSLTA.ns "http://www.w3.org/1999/XSL/TransformAlias">
<!ENTITY XSLFO.ns "http://www.w3.org/1999/XSL/Format">
<!ENTITY copy "&#169;">
<!ENTITY trade "&#8482;">
<!ENTITY deg "&#x00b0;">
<!ENTITY gt "&#62;">
<!ENTITY sup2 "&#x00b2;">
<!ENTITY frac14 "&#x00bc;">
<!ENTITY quot "&#34;">
<!ENTITY frac12 "&#x00bd;">
<!ENTITY euro "&#x20ac;">
<!ENTITY Omega "&#937;">
]>

<xsl:stylesheet 
	xmlns:fox="http://xmlgraphics.apache.org/fop/extensions"
	xmlns:svg="http://www.w3.org/2000/svg"
	xmlns:fo="http://www.w3.org/1999/XSL/Format" version="1.1"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:saxon="http://icl.com/saxon" extension-element-prefixes="saxon"
	xmlns:xslfast="http://www.xslfast.com">


<xsl:template match="Publication">
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
<fo:layout-master-set>
<fo:simple-page-master master-name="pagemaster1" page-height="29.7cm" page-width="21.02cm" margin-top="0.35cm" margin-left="0.35cm" margin-bottom="0.35cm" margin-right="0.21cm" reference-orientation="0">
<xsl:variable name="backgroundImageRepeat">null</xsl:variable><fo:region-body margin-left="3.06cm" margin-top="4.32cm" margin-bottom="1.12cm" margin-right="0.7cm"  background-position-horizontal="null" background-position-vertical="null" />
<fo:region-before extent="4.32cm" precedence="true" />
<fo:region-after extent="1.12cm" precedence="true" />
<fo:region-start extent="3.06cm" />
<fo:region-end extent="0.7cm" />
</fo:simple-page-master>
</fo:layout-master-set>
<fo:bookmark-tree>
</fo:bookmark-tree>
<fo:page-sequence master-reference="pagemaster1">
<xsl:attribute name="force-page-count">no-force</xsl:attribute>
<fo:static-content flow-name="xsl-region-before">
<fo:block-container position="absolute" top="-0.35cm" left="-0.35cm" height="29.77cm" width="3.02cm" background-color="#999999">
<fo:block />
</fo:block-container>
<fo:block-container position="absolute" top="-0.35cm" left="-0.35cm" height="1.12cm" width="21.16cm" background-color="#ff0000">
<fo:block />
</fo:block-container>
<fo:block-container  text-align="start" display-align="before" position="absolute" top="-0.18cm" left="17.99cm" height="0.67cm" width="3.02cm" reference-orientation="0">
<fo:block  padding-bottom="0.0cm" start-indent="0.0cm" end-indent="0.0cm" padding-top="0.0cm" padding="0.0cm" keep-together="auto" >
<xsl:variable name="xslfast_filename">input/Tutorial/img/xsl_logo_neu.jpg</xsl:variable>
<fo:external-graphic src="url({$xslfast_filename})" position="relative" top="-0.18cm" left="17.99cm" content-height="0.67cm" content-width="3.02cm" scaling="uniform"/>
</fo:block>
</fo:block-container>
<xsl:variable name="backgroundImageTextFlowVariable0">
</xsl:variable>
<fo:block-container position="absolute" top="0.95cm" left="3.09cm" height="2.88cm" width="16.59cm" display-align="before" reference-orientation="0">
<fo:block linefeed-treatment="ignore" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0cm" start-indent="0.0cm" end-indent="0.0cm" padding-top="0.0cm" padding="0.0cm" line-height="1.27cm" white-space-collapse="false"  hyphenate="false" language="en"  text-align="center" position="relative" top="0.95cm" left="3.09cm" height="2.88cm" width="16.59cm" keep-together="auto"  letter-spacing="normal" word-spacing="normal">
<fo:block text-align="right" hyphenate="false" language="en" >
<fo:inline color="#000000" font-family="Arial" font-size="18.0pt" font-weight="bold">
<xsl:text>Example 17</xsl:text></fo:inline>
</fo:block>
<fo:block hyphenate="false" language="en" >
<fo:inline color="#000000" font-family="Arial" font-size="30.0pt" font-weight="bold">
<xsl:text>Text</xsl:text></fo:inline>
</fo:block>
</fo:block>
</fo:block-container>
<fo:block-container position="absolute" top="4.01cm" left="-0.35cm" height="0.25cm" width="21.16cm" background-color="#ff0000">
<fo:block />
</fo:block-container>
<fo:block-container  text-align="start" display-align="before" position="absolute" top="1.19cm" left="-0.04cm" height="2.21cm" width="2.39cm" reference-orientation="0">
<fo:block  padding-bottom="0.0cm" start-indent="0.0cm" end-indent="0.0cm" padding-top="0.0cm" padding="0.0cm" keep-together="auto" >
<xsl:variable name="xslfast_filename">input/Tutorial/img/box_xslfast.jpg</xsl:variable>
<fo:external-graphic src="url({$xslfast_filename})" position="relative" top="1.19cm" left="-0.04cm" content-height="2.21cm" content-width="2.39cm" scaling="uniform"/>
</fo:block>
</fo:block-container>
<fo:block-container left="-0.53cm" top="-0.53cm" width="21.33cm" height="0.53cm" position="absolute">
  <fo:block>
    <fo:instream-foreign-object>
      <svg:svg width="21.33cm" height="0.53cm">
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="0,4 10,4"/>
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="5,0 5,10"/>
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="597.0,4 607.0,4"/>
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="602.0,0 602.0,10"/>
      </svg:svg>
    </fo:instream-foreign-object>
  </fo:block>
</fo:block-container></fo:static-content>
<fo:static-content flow-name="xsl-region-after">
<fo:block-container position="absolute" top="0.32cm" left="18.52cm" height="1.02cm" width="1.23cm" background-color="#999999" display-align="before" reference-orientation="0">
<fo:block background-color="#999999" text-align="center" color="#000000" font-family="Arial" font-size="10.0pt" font-weight="bold" padding-bottom="0.0cm" start-indent="0.0cm" end-indent="0.0cm" padding-top="0.0cm" padding="0.0cm" position="relative" top="0.32cm" left="18.52cm" height="1.02cm" width="1.23cm" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="ignore" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en" ><fo:page-number/></fo:block>
</fo:block-container>
<fo:block-container position="absolute" top="0.49cm" left="9.42cm" height="0.91cm" width="8.22cm" display-align="before" reference-orientation="0">
<fo:block text-align="start" color="#666666" font-family="Arial" font-size="10.0pt" font-weight="bold" padding-bottom="0.0cm" start-indent="0.0cm" end-indent="0.0cm" padding-top="0.0cm" padding="0.0cm" position="relative" top="0.49cm" left="9.42cm" height="0.91cm" width="8.22cm" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="ignore" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en" ><fo:basic-link external-destination="url(http://www.xslfast.com)">http://www.xslfast.com</fo:basic-link></fo:block>
</fo:block-container>
<fo:block-container position="absolute" top="0.84cm" left="-0.53cm" width="22.04cm" height="0.91cm" >
 <fo:block  keep-together="auto" >
  <fo:instream-foreign-object>
   <svg:svg xmlns:svg="http://www.w3.org/2000/svg" width = "21.51cm" height="0.39cm">
    <svg:g style="stroke:#ff0000;  fill: none; stroke-dasharray: none; stroke-opacity: 1; stroke-width:0.11cm">
     <svg:line  x1="21.23cm" y1="0.11cm" x2="0.11cm" y2="0.11cm" />
    </svg:g>
   </svg:svg>
  </fo:instream-foreign-object>
 </fo:block>
</fo:block-container>
<fo:block-container left="-0.53cm" top="0.0cm" width="21.33cm" height="1.65cm" position="absolute">
  <fo:block>
    <fo:instream-foreign-object>
      <svg:svg width="21.33cm" height="1.65cm">
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="0,40.0 10,40.0"/>
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="5,35.0 5,45.0"/>
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="597.0,40.0 607.0,40.0"/>
        <svg:polyline fill="none" stroke="grey" stroke-width="0.02cm" points="602.0,35.0 602.0,45.0"/>
      </svg:svg>
    </fo:instream-foreign-object>
  </fo:block>
</fo:block-container></fo:static-content>
<fo:static-content flow-name="xsl-region-start">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="xsl-region-end">
  <fo:block/>
</fo:static-content>
<fo:flow flow-name="xsl-region-body">
<fo:block/>
<xsl:variable name="backgroundImageTextFlowVariable1">
</xsl:variable>
<fo:block-container position="absolute" top="0.14cm" left="0.04cm" height="11.11cm" width="16.59cm" background-color="#ccccff" display-align="before" reference-orientation="0">
<fo:block linefeed-treatment="ignore" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0cm" start-indent="0.18cm" end-indent="0.0cm" padding-top="0.18cm" line-height="0.49cm" white-space-collapse="false"  hyphenate="false" language="en"  text-align="start" position="relative" top="0.14cm" left="0.04cm" height="11.11cm" width="16.59cm" keep-together="auto"  color="#000000" font-family="Arial" font-size="12.0pt" letter-spacing="normal" word-spacing="normal">
<fo:block hyphenate="false" language="en" >
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
<xsl:text>This is a text with footnotes</xsl:text></fo:inline>
</fo:block>
<fo:block hyphenate="false" language="en" >
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
</fo:inline>
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
<xsl:text>Short description with footnote: </xsl:text></fo:inline>
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
<xsl:value-of disable-output-escaping="no" select="ProductGroup/ProductGroup/DescShort"/>
</fo:inline>
</fo:block>
<fo:block hyphenate="false" language="en" >
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
</fo:inline>
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
<xsl:text>Product short description with another footnote: </xsl:text></fo:inline>
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
<xsl:value-of disable-output-escaping="no" select="ProductGroup/ProductGroup/Product/DescShort"/>
</fo:inline>
</fo:block>
<fo:block hyphenate="false" language="en" >
<fo:inline background-color="transparent" color="#000000" font-family="Arial" font-size="12.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
</fo:block>
</fo:block-container>
<fo:block-container position="absolute" top="12.58cm" left="0.7cm" height="1.12cm" width="5.87cm" display-align="before" reference-orientation="0">
<fo:block text-align="start" color="#000000" font-family="Arial" font-size="11.0pt" padding-bottom="0.0cm" start-indent="0.0cm" end-indent="0.0cm" padding-top="0.0cm" padding="0.0cm" position="relative" top="12.58cm" left="0.7cm" height="1.12cm" width="5.87cm" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:text>Text 1</xsl:text>
<xsl:value-of select="LayoutType"/></fo:block>
</fo:block-container>
<xsl:if test='position()=last()'>
  <fo:block id="lastPage"/>
</xsl:if>
</fo:flow>
</fo:page-sequence>
</fo:root>
</xsl:template>
<xsl:template match="include-xsl-fo">
    <xsl:copy-of select="@*"/>
</xsl:template>
<xsl:template name="xslfast_replaceString" >
	<xsl:param name="text" />
	<xsl:param name="textToReplace" />
	<xsl:param name="withWhat" />
	<xsl:choose>
		<xsl:when test="contains($text,$textToReplace)">
		    <xsl:value-of select="concat(substring-before($text,$textToReplace),$withWhat)"/>
		    <xsl:call-template name="xslfast_replaceString">
				<xsl:with-param name="text" select="substring-after($text,$textToReplace)"/>
				<xsl:with-param name="textToReplace" select="$textToReplace"/>
				<xsl:with-param name="withWhat" select="$withWhat"/>
		  </xsl:call-template>
		</xsl:when>
		<xsl:otherwise>
		    <xsl:value-of select="$text"/>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template></xsl:stylesheet>
